### ISSUE TITLE
Not getting factsheet when publishing instantAction factsheetRequest

### ISSUE THREAD

**Issue by ainhoaarnaiz** [inorbit-ai/vda5050_adapter_examples#11]
Hi,
I am trying to retrieve the factsheet of the turtlebot 3 because I would like to see an actual example of it. However, when publishing the instant action factsheetRequest, I get an error. I am unsure if I have added all the needed parameters and if they are correct:

{ 
    "version": "2.0.0", 
    "manufacturer": "OSRF", 
    "serialNumber": "TB3_1", 
    "actions": [ 
        { 
            "actionType": "factsheetRequest", 
            "actionId": "'$(cat /proc/sys/kernel/random/uuid)'", 
            "blockingType": "NONE", 
            "actionParameters": [] 
        } 
    ] 
}

This is the error I get:
![error](https://github.com/inorbit-ai/vda5050_adapter_examples/assets/128591235/9ca83aa9-728f-490f-87fb-3b6c15f45f0b)

Any clue? Thank you very much!

**Comment by leandropineda** [comment]
Hi @aarnaizl.

The factsheet should be published, see https://github.com/inorbit-ai/ros_amr_interop/blob/galactic-devel/vda5050_connector/vda5050_connector/vda5050_controller.py#L713. I think the issue is with the action ID. From the screenshot you shared I can see that the action id is `'$(cat /proc/sys/kernel/random/uuid)'`, but it should be an UUID. Do you get the same error after fixing that?

**Comment by ainhoaarnaiz** [comment]
Hi @leandropineda 
So I have taken a closer look at the error and decided to change this part of the tb3_adapter.py from this:
https://github.com/inorbit-ai/vda5050_adapter_examples/blob/230d17385df74a9702ac84f51f8e582528dbfa77/vda5050_tb3_adapter/vda5050_tb3_adapter/tb3_adapter.py#L96-L100
to this:
```
self.supported_actions_srv = self.create_service(
   srv_type=SupportedActions,
   srv_name=base_interface_name + self._supported_actions_svc_srv,
   callback=self.get_supported_actions_callback,
)
```
and created a simple callback function:
```
def get_supported_actions_callback(self, request, response):
    lambda _: self.get_logger().info("Supported actions request")
    return response
```

After fixing this, I have noticed that when factsheetRequest is published, the factsheet is not published in MQTT under the topic _/uagv/v1/OSRF/TB3_1/factsheet_ or anything similar. Instead, I had previously run the command `ros2 topic echo /uagv/v1/OSRF/TB3_1/factsheet` on a new terminal and was able to see it there. Here is the output:

```
header_id: 1
timestamp: '2023-06-29T11:26:21.801Z'
version: 2.0.0
manufacturer: OSRF
serial_number: TB3_1
type_specification:
  series_name: robot_number
  series_description: ''
  agv_kinematic: OMNI
  agv_class: CARRIER
  max_load_mass: 0.0
  localization_types:
  - REFLECTOR
  navigation_types:
  - AUTONOMOUS
physical_parameters:
  speed_min: 0.0
  speed_max: 0.0
  acceleration_max: 0.0
  deceleration_max: 0.0
  height_min: 0.0
...
```
However, I am unsure if this is the expected output. Is it intended to publish the message only on the ROS2 topic _/uagv/v1/OSRF/TB3_1/factsheet_? Or should it also be published to MQTT?

Here is a screenshot of the execution (something similar happens with stateRequest):
![Screenshot from 2023-06-29 14-05-38](https://github.com/inorbit-ai/vda5050_adapter_examples/assets/128591235/40ee9a37-3eb7-43b6-95bc-d76524c49275)
